BLACKLISTED_SKILLS = ["experience_skill_carpentry", "experience_skill_runecrafting"]

COOP_UPGRADES_TEMPLATE = {
    "minion_slots": {"name": "Minion Slots", "level": 0, "max_level": 5},
    "island_size": {"name": "Island Size", "level": 0, "max_level": 10},
    "coins_allowance": {"name": "Coins Allowance", "level": 0, "max_level": 5},
    "coop_slots": {"name": "Coop Slots", "level": 0, "max_level": 3},
    "guests_count": {"name": "Guests Count", "level": 0, "max_level": 5},
}

JACOBS_MEDALS_TEMPLATE = {"bronze": 0, "silver": 0, "gold": 0}

JACOBS_UPGRADES_TEMPLATE = {
    "double_drops": {"level": 0, "max_level": 15},
    "farming_level_cap": {"level": 0, "max_level": 10},
}

JACOBS_INFO_TEMPLATE = {
    "POTATO_ITEM": {"name": "Potato", "gold_status": False, "highscore": 0},
    "CARROT_ITEM": {"name": "Carrot", "gold_status": False, "highscore": 0},
    "NETHER_STALK": {"name": "Nether Wart", "gold_status": False, "highscore": 0},
    "SUGAR_CANE": {"name": "Sugarcane", "gold_status": False, "highscore": 0},
    "MUSHROOM_COLLECTION": {"name": "Mushroom", "gold_status": False, "highscore": 0},
    "PUMPKIN": {"name": "Pumpkin", "gold_status": False, "highscore": 0},
    "MELON": {"name": "Melon", "gold_status": False, "highscore": 0},
    "INK_SACK": {"name": "Cocoa Beans", "gold_status": False, "highscore": 0},
    "WHEAT": {"name": "Wheat", "gold_status": False, "highscore": 0},
    "CACTUS": {"name": "Cactus", "gold_status": False, "highscore": 0},
}

SLAYER_TEMPLATE = {
    "zombie": {"xp": 0, "level": 0, "name": "Revenant"},
    "spider": {"xp": 0, "level": 0, "name": "Tarantula"},
    "wolf": {"xp": 0, "level": 0, "name": "Sven"},
}

DUNGEON_XP_TABLE = {
    0: 0,
    1: 50,
    2: 125,
    3: 235,
    4: 395,
    5: 625,
    6: 955,
    7: 1425,
    8: 2095,
    9: 3045,
    10: 4385,
    11: 6275,
    12: 8940,
    13: 12700,
    14: 17960,
    15: 25340,
    16: 35640,
    17: 50040,
    18: 70040,
    19: 97640,
    20: 135640,
    21: 188140,
    22: 259640,
    23: 356640,
    24: 488640,
    25: 668640,
    26: 911640,
    27: 1239640,
    28: 1684640,
    29: 2284640,
    30: 3084640,
    31: 4149640,
    32: 5559640,
    33: 7459640,
    34: 9959640,
    35: 13259640,
    36: 17559640,
    37: 23159640,
    38: 30359640,
    39: 39559640,
    40: 51559640,
    41: 66559640,
    42: 85559640,
    43: 109559640,
    44: 139559640,
    45: 177559640,
    46: 225559640,
    47: 285559640,
    48: 360559640,
    49: 453559640,
    50: 569809640,
}

DUNGEON_INDIVIDUAL_XP_TABLE = {
    0: 0,
    1: 50,
    2: 75,
    3: 110,
    4: 160,
    5: 230,
    6: 330,
    7: 470,
    8: 670,
    9: 950,
    10: 1340,
    11: 1890,
    12: 2665,
    13: 3760,
    14: 5260,
    15: 7380,
    16: 10300,
    17: 14400,
    18: 20000,
    19: 27600,
    20: 38000,
    21: 52500,
    22: 71500,
    23: 97000,
    24: 132000,
    25: 180000,
    26: 243000,
    27: 328000,
    28: 445000,
    29: 600000,
    30: 800000,
    31: 1065000,
    32: 1410000,
    33: 1900000,
    34: 2500000,
    35: 3300000,
    36: 4300000,
    37: 5600000,
    38: 7200000,
    39: 9200000,
    40: 12000000,
    41: 15000000,
    42: 19000000,
    43: 24000000,
    44: 30000000,
    45: 38000000,
    46: 48000000,
    47: 60000000,
    48: 75000000,
    49: 93000000,
    50: 116250000,
}

SKILL_XP_TABLE = {
    0: 0,
    1: 50,
    2: 175,
    3: 375,
    4: 675,
    5: 1175,
    6: 1925,
    7: 2925,
    8: 4425,
    9: 6425,
    10: 9925,
    11: 14925,
    12: 22425,
    13: 32425,
    14: 47425,
    15: 67425,
    16: 97425,
    17: 147425,
    18: 222425,
    19: 322425,
    20: 522425,
    21: 822425,
    22: 1222425,
    23: 1722425,
    24: 2322425,
    25: 3022425,
    26: 3822425,
    27: 4722425,
    28: 5722425,
    29: 6822425,
    30: 8022425,
    31: 9322425,
    32: 10722425,
    33: 12222425,
    34: 13822425,
    35: 15522425,
    36: 17322425,
    37: 19222425,
    38: 21222425,
    39: 23322425,
    40: 25522425,
    41: 27822425,
    42: 30222425,
    43: 32722425,
    44: 35322425,
    45: 38072425,
    46: 40972425,
    47: 44072425,
    48: 47472425,
    49: 51172425,
    50: 55172425,
    51: 59472425,
    52: 64072425,
    53: 68972425,
    54: 74172425,
    55: 79672425,
    56: 85472425,
    57: 91572425,
    58: 97972425,
    59: 104672425,
    60: 111672425,
}

SKILL_INDIVIDUAL_XP_TABLE = {
    0: 0,
    1: 50,
    2: 125,
    3: 200,
    4: 300,
    5: 500,
    6: 750,
    7: 1000,
    8: 1500,
    9: 2000,
    10: 3500,
    11: 5000,
    12: 7500,
    13: 10000,
    14: 15000,
    15: 20000,
    16: 30000,
    17: 50000,
    18: 75000,
    19: 100000,
    20: 200000,
    21: 300000,
    22: 400000,
    23: 500000,
    24: 600000,
    25: 700000,
    26: 800000,
    27: 900000,
    28: 1000000,
    29: 1100000,
    30: 1200000,
    31: 1300000,
    32: 1400000,
    33: 1500000,
    34: 1600000,
    35: 1700000,
    36: 1800000,
    37: 1900000,
    38: 2000000,
    39: 2100000,
    40: 2200000,
    41: 2300000,
    42: 2400000,
    43: 2500000,
    44: 2600000,
    45: 2750000,
    46: 2900000,
    47: 3100000,
    48: 3400000,
    49: 3700000,
    50: 4000000,
    51: 4300000,
    52: 4600000,
    53: 4900000,
    54: 5200000,
    55: 5500000,
    56: 5800000,
    57: 6100000,
    58: 6400000,
    59: 6700000,
    60: 7000000,
}

RUNECRAFTING_XP_TABLE = {
    0: 0,
    1: 50,
    2: 150,
    3: 275,
    4: 435,
    5: 635,
    6: 885,
    7: 1200,
    8: 1600,
    9: 2100,
    10: 2725,
    11: 3510,
    12: 4510,
    13: 5760,
    14: 7325,
    15: 9325,
    16: 11825,
    17: 14950,
    18: 18950,
    19: 23950,
    20: 30200,
    21: 38050,
    22: 47850,
    23: 60100,
    24: 75400,
    25: 94500,
}

RUNECRAFTING_INDIVIDUAL_XP_TABLE = {
    0: 0,
    1: 50,
    2: 100,
    3: 125,
    4: 160,
    5: 200,
    6: 250,
    7: 315,
    8: 400,
    9: 500,
    10: 625,
    11: 785,
    12: 1000,
    13: 1250,
    14: 1565,
    15: 2000,
    16: 2500,
    17: 3125,
    18: 4000,
    19: 5000,
    20: 6250,
    21: 7850,
    22: 9800,
    23: 12250,
    24: 15300,
    25: 19100,
}

DUNGEON_CLASS_XP_TEMPLATE = {
    "mage": 0,
    "archer": 0,
    "tank": 0,
    "healer": 0,
    "berserk": 0,
}

DUNGEON_FLOOR_INFO_TEMPLATE = {
    "0": {
        "name": "Entrance",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "1": {
        "name": "Floor 1",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "2": {
        "name": "Floor 2",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "3": {
        "name": "Floor 3",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "4": {
        "name": "Floor 4",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "5": {
        "name": "Floor 5",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "6": {
        "name": "Floor 6",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
    "7": {
        "name": "Floor 7",
        "best_score": 0,
        "fastest_time_s": 0,
        "fastest_time_s_plus": 0,
        "completions": 0,
    },
}

SLAYER_LEVEL = {
    "zombie": {
        0: 0,
        1: 5,
        2: 25,
        3: 200,
        4: 1000,
        5: 5000,
        6: 20000,
        7: 100000,
        8: 400000,
        9: 1000000,
    },
    "spider": {
        0: 0,
        1: 5,
        2: 25,
        3: 200,
        4: 1000,
        5: 5000,
        6: 20000,
        7: 100000,
        8: 400000,
        9: 1000000,
    },
    "wolf": {
        0: 0,
        1: 10,
        2: 30,
        3: 250,
        4: 1500,
        5: 5000,
        6: 20000,
        7: 100000,
        8: 400000,
        9: 1000000,
    },
}

SKILLS_TEMPLATE = {
    "experience_skill_combat": {"xp": 0, "max_level": 60},
    "experience_skill_mining": {"xp": 0, "max_level": 60},
    "experience_skill_farming": {"xp": 0, "max_level": 60},
    "experience_skill_fishing": {"xp": 0, "max_level": 50},
    "experience_skill_foraging": {"xp": 0, "max_level": 50},
    "experience_skill_taming": {"xp": 0, "max_level": 50},
    "experience_skill_alchemy": {"xp": 0, "max_level": 50},
    "experience_skill_enchanting": {"xp": 0, "max_level": 60},
    "experience_skill_runecrafting": {"xp": 0, "max_level": 25},
    "experience_skill_carpentry": {"xp": 0, "max_level": 50},
}

MILESTONE_TABLE = {
    "rock": {
        "Rock": 0,
        "Common Rock": 2500,
        "Uncommon Rock": 7500,
        "Rare Rock": 20000,
        "Epic Rock": 100000,
        "Legendary Rock": 250000,
    },
    "dolphin": {
        "Dolphin": 0,
        "Common Dolphin": 250,
        "Uncommon Dolphin": 1000,
        "Rare Dolphin": 2500,
        "Epic Dolphin": 5000,
        "Legendary Dolphin": 10000,
    },
}

SKYBLOCK_LEADERBOARDS = {
    "Dungeons Catacombs Floor 7 Most Damage Healer": "dungeons_catacombs_floor_7_most_damage_healer",
    "Dungeon Hub Giant Mushroom No Abilities No Return Best Time": "dungeon_hub_giant_mushroom_no_abilities_no_return_best_time",
    "Kills Frosty The Snowman": "kills_frosty_the_snowman",
    "Deaths Pack Wolf": "deaths_pack_wolf",
    "Deaths Spirit Bull": "deaths_spirit_bull",
    "Deaths Ghast": "deaths_ghast",
    "Deaths Professor": "deaths_professor",
    "Kills Sea Leech": "kills_sea_leech",
    "Auctions Sold Legendary": "auctions_sold_legendary",
    "Kills Emerald Slime": "kills_emerald_slime",
    "Skill Farming Xp": "skill_farming_xp",
    "Chicken Race Best Time": "chicken_race_best_time",
    "Kills Spirit Miniboss": "kills_spirit_miniboss",
    "Mythos Burrows Dug Next": "mythos_burrows_dug_next",
    "Collection Huge Mushroom 1": "collection_huge_mushroom_1",
    "Kills Mimic": "kills_mimic",
    "Collection Sapling:3": "collection_sapling:3",
    "Kills Tiger Shark": "kills_tiger_shark",
    "Collection Coal Block": "collection_coal_block",
    "Deaths Shadow Assassin": "deaths_shadow_assassin",
    "Kills Monster Of The Deep": "kills_monster_of_the_deep",
    "Deaths Skeletor Prime": "deaths_skeletor_prime",
    "Kills Watcher Scarf": "kills_watcher_scarf",
    "Kills Scarf Warrior": "kills_scarf_warrior",
    "Deaths Scary Jerry": "deaths_scary_jerry",
    "Ink Sac Collection": "collection_ink_sack",
    "Kills Grim Reaper": "kills_grim_reaper",
    "Dungeons Catacombs Floor 6 Best Score": "dungeons_catacombs_floor_6_best_score",
    "Collection Red Rose:3": "collection_red_rose:3",
    "Dungeons Catacombs Floor 1 Mobs Killed": "dungeons_catacombs_floor_1_mobs_killed",
    "Deaths Spider Jockey": "deaths_spider_jockey",
    "Kills Spirit Chicken": "kills_spirit_chicken",
    "Deaths Spirit Chicken": "deaths_spirit_chicken",
    "Collection Sapling:1": "collection_sapling:1",
    "Dungeon Hub Crystal Core Nothing No Return Best Time": "dungeon_hub_crystal_core_nothing_no_return_best_time",
    "Kills Horseman Bat": "kills_horseman_bat",
    "Deaths Nurse Shark": "deaths_nurse_shark",
    "Shredder Bait": "shredder_bait",
    "Deaths Crypt Undead Bernhard": "deaths_crypt_undead_bernhard",
    "Nether Quartz Collection": "collection_quartz",
    "Deaths Zombie Villager": "deaths_zombie_villager",
    "Dungeons Secrets": "dungeons_secrets",
    "Deaths Scarf Warrior": "deaths_scarf_warrior",
    "Kills King Midas": "kills_king_midas",
    "Kills Watcher Giant Laser": "kills_watcher_giant_laser",
    "Deaths Sea Leech": "deaths_sea_leech",
    "Dungeons Catacombs Floor 1 Most Healing": "dungeons_catacombs_floor_1_most_healing",
    "Kills Cellar Spider": "kills_cellar_spider",
    "Deaths Crypt Undead Judg3": "deaths_crypt_undead_judg3",
    "Dungeons Catacombs Floor 3 Mobs Killed": "dungeons_catacombs_floor_3_mobs_killed",
    "Deaths Crypt Undead Skyerzz": "deaths_crypt_undead_skyerzz",
    "Dungeons Catacombs Floor 2 Watcher Kills": "dungeons_catacombs_floor_2_watcher_kills",
    "Auctions No Bids": "auctions_no_bids",
    "Deaths Superior Dragon": "deaths_superior_dragon",
    "Deaths Magma Cube Boss": "deaths_magma_cube_boss",
    "Deaths Goblin Battler": "deaths_goblin_battler",
    "Auctions Completed": "auctions_completed",
    "Deaths Silverfish": "deaths_silverfish",
    "Kills Goblin Battler": "kills_goblin_battler",
    "Kills Crypt Undead Orangemarshall": "kills_crypt_undead_orangemarshall",
    "Dungeons Catacombs Floor 3 Fastest Time S+": "dungeons_catacombs_floor_3_fastest_time_s+",
    "Kills Lost Adventurer": "kills_lost_adventurer",
    "Dungeon Hub Crystal Core Anything With Return Best Time": "dungeon_hub_crystal_core_anything_with_return_best_time",
    "Dungeons Catacombs Entrance Most Damage Tank": "dungeons_catacombs_entrance_most_damage_tank",
    "Mythos Burrows Dug Treasure Common": "mythos_burrows_dug_treasure_COMMON",
    "Auctions Bought Mythic": "auctions_bought_mythic",
    "Mythos Burrows Chains Complete Common": "mythos_burrows_chains_complete_COMMON",
    "Dungeons Catacombs Floor 5 Fastest Time": "dungeons_catacombs_floor_5_fastest_time",
    "Dungeons Catacombs Floor 2 Times Played": "dungeons_catacombs_floor_2_times_played",
    "Deaths Soul Of The Alpha": "deaths_soul_of_the_alpha",
    "Deaths Pack Spirit": "deaths_pack_spirit",
    "Deaths Lost Adventurer": "deaths_lost_adventurer",
    "Skill Fishing Xp": "skill_fishing_xp",
    "Collection Sapling:4": "collection_sapling:4",
    "Collection Red Rose:6": "collection_red_rose:6",
    "Kills Goblin Weakling Melee": "kills_goblin_weakling_melee",
    "Deaths Professor Mage Guardian": "deaths_professor_mage_guardian",
    "Deaths Enderman": "deaths_enderman",
    "Deaths Skeleton": "deaths_skeleton",
    "Auctions Created": "auctions_created",
    "Spider Eye Collection": "collection_spider_eye",
    "Deaths Minotaur": "deaths_minotaur",
    "Dungeons Catacombs Floor 1 Times Played": "dungeons_catacombs_floor_1_times_played",
    "Kills Lapis Zombie": "kills_lapis_zombie",
    "Kills Horseman Zombie": "kills_horseman_zombie",
    "Mythos Burrows Chains Complete": "mythos_burrows_chains_complete",
    "Mythos Burrows Chains Complete Legendary": "mythos_burrows_chains_complete_LEGENDARY",
    "Total Dragon Kills": "total_dragon_kills",
    "Kills Crypt Undead Bembo": "kills_crypt_undead_bembo",
    "Kills Magma Cube": "kills_magma_cube",
    "Collection Rabbit Hide": "collection_rabbit_hide",
    "Sneaky Creeper Kills": "kills_invisible_creeper",
    "Deaths Endermite": "deaths_endermite",
    "Mythos Burrows Dug Next Legendary": "mythos_burrows_dug_next_LEGENDARY",
    "Kills Crypt Undead Skyerzz": "kills_crypt_undead_skyerzz",
    "Dungeons Catacombs Floor 4 Best Score": "dungeons_catacombs_floor_4_best_score",
    "Dungeons Catacombs Entrance Fastest Time": "dungeons_catacombs_entrance_fastest_time",
    "Slimeball Collection": "collection_slime_ball",
    "Kills Pigman": "kills_pigman",
    "Deaths Diamond Guy": "deaths_diamond_guy",
    "Dungeons Catacombs Floor 6 Watcher Kills": "dungeons_catacombs_floor_6_watcher_kills",
    "Kills Nurse Shark": "kills_nurse_shark",
    "Kills Crypt Undead Thorlon": "kills_crypt_undead_thorlon",
    "Dungeons Catacombs Floor 7 Most Mobs Killed": "dungeons_catacombs_floor_7_most_mobs_killed",
    "Dungeons Catacombs Floor 2 Best Score": "dungeons_catacombs_floor_2_best_score",
    "Dungeons Tank Xp": "dungeons_tank_xp",
    "Dungeons Catacombs Entrance Most Damage Berserk": "dungeons_catacombs_entrance_most_damage_berserk",
    "Kills Pig": "kills_pig",
    "Kills Crypt Undead Luckykessie": "kills_crypt_undead_luckykessie",
    "Deaths Watcher Summon Undead": "deaths_watcher_summon_undead",
    "Deaths Crypt Undead Plancke": "deaths_crypt_undead_plancke",
    "Deaths Spirit Miniboss": "deaths_spirit_miniboss",
    "Collection Prismarine:1": "collection_prismarine:1",
    "Deaths Redstone Pigman": "deaths_redstone_pigman",
    "Dungeons Catacombs Floor 1 Most Damage Berserk": "dungeons_catacombs_floor_1_most_damage_berserk",
    "Most Winter Cannonballs Hit": "most_winter_cannonballs_hit",
    "Deaths Goblin Murderlover": "deaths_goblin_murderlover",
    "Deaths Crypt Undead": "deaths_crypt_undead",
    "Deaths Parasite": "deaths_parasite",
    "Average Level": "average_level",
    "Deaths Crypt Undead Blockskey": "deaths_crypt_undead_blockskey",
    "Deaths Super Tank Zombie": "deaths_super_tank_zombie",
    "Auctions Bought Common": "auctions_bought_common",
    "Dungeons Catacombs Floor 6 Most Healing": "dungeons_catacombs_floor_6_most_healing",
    "Kills Diamond Guy": "kills_diamond_guy",
    "Kills Old Dragon": "kills_old_dragon",
    "Kills Catfish": "kills_catfish",
    "Deaths Splitter Spider Silverfish": "deaths_splitter_spider_silverfish",
    "Shredder Fished": "shredder_fished",
    "Kills Sea Walker": "kills_sea_walker",
    "Sneaky Creeper Deaths": "deaths_invisible_creeper",
    "Collection Glass": "collection_glass",
    "Mythos Burrows Dug Next Rare": "mythos_burrows_dug_next_RARE",
    "Collection Sapling": "collection_sapling",
    "Kills Skeleton Master": "kills_skeleton_master",
    "Deaths \uf701lost Adventure": "deaths_\uf701lost_adventure",
    "Lapis Lazuli Collection": "collection_ink_sack:4",
    "Deaths Cellar Spider": "deaths_cellar_spider",
    "Netherrack Collection": "collection_netherrack",
    "Deaths Crypt Undead Deadorkai": "deaths_crypt_undead_deadorkai",
    "Kills Crypt Undead": "kills_crypt_undead",
    "Deaths Witch": "deaths_witch",
    "Kills Crypt Undead Ladybleu": "kills_crypt_undead_ladybleu",
    "Deaths Drowning": "deaths_drowning",
    "Kills Wither Gourd": "kills_wither_gourd",
    "Dungeon Hub Giant Mushroom No Pearls No Return Best Time": "dungeon_hub_giant_mushroom_no_pearls_no_return_best_time",
    "Deaths Water Hydra": "deaths_water_hydra",
    "Kills Watcher Summon Undead": "kills_watcher_summon_undead",
    "Ghast Tear Collection": "collection_ghast_tear",
    "Kills Wraith": "kills_wraith",
    "Dungeon Hub Precursor Ruins Anything No Return Best Time": "dungeon_hub_precursor_ruins_anything_no_return_best_time",
    "Melon Collection": "collection_melon",
    "Dungeons Catacombs Floor 4 Most Damage Mage": "dungeons_catacombs_floor_4_most_damage_mage",
    "Most Winter Damage Dealt": "most_winter_damage_dealt",
    "Deaths Crypt Undead Christian": "deaths_crypt_undead_christian",
    "Deaths Skeleton Grunt": "deaths_skeleton_grunt",
    "Skill Carpentry Xp": "skill_carpentry_xp",
    "Dungeons Catacombs Floor 3 Fastest Time S": "dungeons_catacombs_floor_3_fastest_time_s",
    "Deaths Bonzo Summon Undead": "deaths_bonzo_summon_undead",
    "Dungeons Catacombs Entrance Most Damage Healer": "dungeons_catacombs_entrance_most_damage_healer",
    "Dungeons Catacombs Floor 4 Mobs Killed": "dungeons_catacombs_floor_4_mobs_killed",
    "Kills Unstable Dragon": "kills_unstable_dragon",
    "Collection Red Rose:5": "collection_red_rose:5",
    "Iron Ingot Collection": "collection_iron_ingot",
    "Dungeons Catacombs Floor 6 Fastest Time S+": "dungeons_catacombs_floor_6_fastest_time_s+",
    "Kills Tentaclees": "kills_tentaclees",
    "Deaths Chicken": "deaths_chicken",
    "Skill Mining Xp": "skill_mining_xp",
    "Kills Witch": "kills_witch",
    "Deaths Crypt Undead Likaos": "deaths_crypt_undead_likaos",
    "Lily Pad Collection": "collection_water_lily",
    "Dungeons Catacombs Entrance Most Healing": "dungeons_catacombs_entrance_most_healing",
    "Dungeons Catacombs Floor 6 Most Damage Berserk": "dungeons_catacombs_floor_6_most_damage_berserk",
    "Dungeons Catacombs Floor 5 Watcher Kills": "dungeons_catacombs_floor_5_watcher_kills",
    "Deaths Spirit Sheep": "deaths_spirit_sheep",
    "Mutton Collection": "collection_mutton",
    "Kills Magma Cube Boss": "kills_magma_cube_boss",
    "Kills Crypt Undead Externalizable": "kills_crypt_undead_externalizable",
    "Dungeons Catacombs Floor 6 Times Played": "dungeons_catacombs_floor_6_times_played",
    "Deaths The Watcher": "deaths_the_watcher",
    "Deaths Watcher": "deaths_watcher",
    "Dungeons Catacombs Floor 2 Most Damage Healer": "dungeons_catacombs_floor_2_most_damage_healer",
    "Kills Player": "kills_player",
    "Kills Weaver Spider": "kills_weaver_spider",
    "Kills Chicken Deep": "kills_chicken_deep",
    "Crypt Ghoul Deaths": "deaths_unburried_zombie",
    "Deaths Spider": "deaths_spider",
    "Deaths Headless Horseman": "deaths_headless_horseman",
    "Kills Bat Spooky": "kills_bat_spooky",
    "Mythos Kills": "mythos_kills",
    "Kills Scarf Archer": "kills_scarf_archer",
    "Dungeons Catacombs Floor 5 Most Mobs Killed": "dungeons_catacombs_floor_5_most_mobs_killed",
    "Kills Scared Skeleton": "kills_scared_skeleton",
    "Collection Red Rose:7": "collection_red_rose:7",
    "Kills Spirit Bat": "kills_spirit_bat",
    "Dungeons Catacombs Floor 6 Most Mobs Killed": "dungeons_catacombs_floor_6_most_mobs_killed",
    "Kills Sea Archer": "kills_sea_archer",
    "Skill Taming Xp": "skill_taming_xp",
    "Kills Vicious Wolf": "kills_vicious_wolf",
    "Kills Watcher Giant Boulder": "kills_watcher_giant_boulder",
    "Deaths Watcher Giant Laser": "deaths_watcher_giant_laser",
    "Deaths Ender Dragon": "deaths_ender_dragon",
    "Deaths Guardian Defender": "deaths_guardian_defender",
    "Feather Collection": "collection_feather",
    "Kills Crypt Undead Friedrich": "kills_crypt_undead_friedrich",
    "Deaths Splitter Spider": "deaths_splitter_spider",
    "Dungeon Hub Crystal Core No Pearls No Return Best Time": "dungeon_hub_crystal_core_no_pearls_no_return_best_time",
    "Deaths Lonely Spider": "deaths_lonely_spider",
    "Dungeons Catacombs Floor 1 Completions": "dungeons_catacombs_floor_1_completions",
    "Dark Oak Wood Collection": "collection_log_2:1",
    "Deaths Revenant Zombie": "deaths_revenant_zombie",
    "Dungeons Catacombs Floor 3 Most Mobs Killed": "dungeons_catacombs_floor_3_most_mobs_killed",
    "Dungeons Catacombs Floor 2 Most Healing": "dungeons_catacombs_floor_2_most_healing",
    "Kills Creeper": "kills_creeper",
    "Auctions Bought Rare": "auctions_bought_rare",
    "Skill Runecrafting Xp": "skill_runecrafting_xp",
    "Dungeon Hub Giant Mushroom Anything No Return Best Time": "dungeon_hub_giant_mushroom_anything_no_return_best_time",
    "Kills Crypt Undead Connorlinfoot": "kills_crypt_undead_connorlinfoot",
    "Kills Frozen Steve": "kills_frozen_steve",
    "Kills Crypt Undead Nitroholic ": "kills_crypt_undead_nitroholic_",
    "Collection Red Rose:8": "collection_red_rose:8",
    "Prismarine Shard Collection": "collection_prismarine_shard",
    "Kills Crypt Witherskeleton": "kills_crypt_witherskeleton",
    "Deaths Suffocation": "deaths_suffocation",
    "Dungeons Catacombs Floor 2 Most Damage Mage": "dungeons_catacombs_floor_2_most_damage_mage",
    "Collection Glowstone": "collection_glowstone",
    "Dungeons Catacombs Floor 2 Most Damage Tank": "dungeons_catacombs_floor_2_most_damage_tank",
    "Leather Collection": "collection_leather",
    "Deaths Zombie Grunt": "deaths_zombie_grunt",
    "Deaths Voracious Spider": "deaths_voracious_spider",
    "Kills Lonely Spider": "kills_lonely_spider",
    "Zealot Kills": "kills_zealot_enderman",
    "Deaths Livid Clone": "deaths_livid_clone",
    "Collection Diamond Block": "collection_diamond_block",
    "Kills Night Respawning Skeleton": "kills_night_respawning_skeleton",
    "Kills Zombie Knight": "kills_zombie_knight",
    "Dungeons Catacombs Floor 3 Most Damage Tank": "dungeons_catacombs_floor_3_most_damage_tank",
    "Deaths Ocelot": "deaths_ocelot",
    "Deaths Crypt Undead Bembo": "deaths_crypt_undead_bembo",
    "Raw Porkchop Collection": "collection_pork",
    "Deaths Super Archer": "deaths_super_archer",
    "Collection Quartz Block": "collection_quartz_block",
    "Deaths Frozen Steve": "deaths_frozen_steve",
    "Total Collected Items": "total_collected_items",
    "Deaths Diamond Skeleton": "deaths_diamond_skeleton",
    "Kills Crypt Undead Robitybobity": "kills_crypt_undead_robitybobity",
    "Dungeons Catacombs Floor 6 Mobs Killed": "dungeons_catacombs_floor_6_mobs_killed",
    "Mushroom Collection": "collection_mushroom_collection",
    "End Race Best Time": "end_race_best_time",
    "Deaths Wither Skeleton": "deaths_wither_skeleton",
    "Deaths Watcher Giant Diamond": "deaths_watcher_giant_diamond",
    "Deaths Sadan": "deaths_sadan",
    "Prismarine Crystals Collection": "collection_prismarine_crystals",
    "Kills Guardian Emperor": "kills_guardian_emperor",
    "Dungeons Catacombs Floor 4 Most Damage Berserk": "dungeons_catacombs_floor_4_most_damage_berserk",
    "Deaths Jockey Skeleton": "deaths_jockey_skeleton",
    "Dungeon Hub Crystal Core No Abilities With Return Best Time": "dungeon_hub_crystal_core_no_abilities_with_return_best_time",
    "Deaths Crypt Undead Chilynn": "deaths_crypt_undead_chilynn",
    "Deaths Strong Dragon": "deaths_strong_dragon",
    "Kills Zombie Soldier": "kills_zombie_soldier",
    "Deaths": "deaths",
    "Kills Ruin Wolf": "kills_ruin_wolf",
    "Collection Sapling:2": "collection_sapling:2",
    "Deaths Grim Reaper": "deaths_grim_reaper",
    "Kills Skeleton Grunt": "kills_skeleton_grunt",
    "Kills Tarantula Broodfather Tier 2": "spider_slayer_boss_kills_tier_1",
    "Kills Revenant Horror Tier 4": "zombie_slayer_boss_kills_tier_3",
    "Collection Huge Mushroom 2": "collection_huge_mushroom_2",
    "Dungeon Hub Giant Mushroom No Pearls With Return Best Time": "dungeon_hub_giant_mushroom_no_pearls_with_return_best_time",
    "Deaths Guardian Emperor": "deaths_guardian_emperor",
    "Kills Howling Spirit": "kills_howling_spirit",
    "Dungeons Catacombs Floor 7 Times Played": "dungeons_catacombs_floor_7_times_played",
    "Deaths Treasure Hoarder": "deaths_treasure_hoarder",
    "Kills Tarantula Broodfather Tier 4": "spider_slayer_boss_kills_tier_3",
    "Mythos Burrows Dug Treasure Epic": "mythos_burrows_dug_treasure_EPIC",
    "Kills Sven Packmaster Tier 4": "wolf_slayer_boss_kills_tier_3",
    "Pufferfish Collection": "collection_raw_fish:3",
    "Redstone Collection": "collection_redstone",
    "Mythos Burrows Dug Treasure Uncommon": "mythos_burrows_dug_treasure_UNCOMMON",
    "Collection Hay Block": "collection_hay_block",
    "Deaths Crypt Undead Minikloon": "deaths_crypt_undead_minikloon",
    "Kills Spirit Sheep": "kills_spirit_sheep",
    "Deaths Great White Shark": "deaths_great_white_shark",
    "Dungeons Catacombs Floor 3 Most Healing": "dungeons_catacombs_floor_3_most_healing",
    "Kills Crypt Undead Agentk": "kills_crypt_undead_agentk",
    "Kills Slime": "kills_slime",
    "Kills Watcher Giant Diamond": "kills_watcher_giant_diamond",
    "Deaths Slime": "deaths_slime",
    "Kills Watcher Giant Bigfoot": "kills_watcher_giant_bigfoot",
    "Deaths Crypt Undead Externalizable": "deaths_crypt_undead_externalizable",
    "Kills Minos Inquisitor": "kills_minos_inquisitor",
    "Bone Collection": "collection_bone",
    "Deaths Young Dragon": "deaths_young_dragon",
    "Kills Brood Mother Cave Spider": "kills_brood_mother_cave_spider",
    "Deaths Crypt Undead Hypixel": "deaths_crypt_undead_hypixel",
    "Dungeons Catacombs Floor 5 Most Damage Berserk": "dungeons_catacombs_floor_5_most_damage_berserk",
    "Auctions Gold Earned": "auctions_gold_earned",
    "Gunpowder Collection": "collection_sulphur",
    "Deaths Crypt Undead Pjoke1": "deaths_crypt_undead_pjoke1",
    "Dungeons Catacombs Floor 7 Most Damage Archer": "dungeons_catacombs_floor_7_most_damage_archer",
    "Deaths Livid": "deaths_livid",
    "Deaths Snowman": "deaths_snowman",
    "Kills Goblin": "kills_goblin",
    "Kills Crypt Undead Revengeee": "kills_crypt_undead_revengeee",
    "Dungeons Catacombs Floor 2 Fastest Time S+": "dungeons_catacombs_floor_2_fastest_time_s+",
    "Deaths Werewolf": "deaths_werewolf",
    "Dungeons Catacombs Floor 5 Times Played": "dungeons_catacombs_floor_5_times_played",
    "Deaths Ancient One": "deaths_ancient_one",
    "Deaths Guardian": "deaths_guardian",
    "Kills Professor Guardian Summon": "kills_professor_guardian_summon",
    "Kills Zombie Commander": "kills_zombie_commander",
    "Dungeons Catacombs Floor 1 Fastest Time S+": "dungeons_catacombs_floor_1_fastest_time_s+",
    "Deaths Player": "deaths_player",
    "Total Sea Creatures Killed": "total_sea_creatures_killed",
    "Kills Blaze": "kills_blaze",
    "Deaths Crypt Undead Alexander": "deaths_crypt_undead_alexander",
    "Deaths Crypt Undead Bloozing": "deaths_crypt_undead_bloozing",
    "Dungeons Catacombs Floor 7 Most Healing": "dungeons_catacombs_floor_7_most_healing",
    "Deaths Kill": "deaths_kill",
    "Clownfish Collection": "collection_raw_fish:2",
    "Auctions Won": "auctions_won",
    "Sponge Collection": "collection_sponge",
    "Deaths Ruin Wolf": "deaths_ruin_wolf",
    "Deaths Obsidian Wither": "deaths_obsidian_wither",
    "Deaths Fireball Magma Cube": "deaths_fireball_magma_cube",
    "Dungeons Catacombs Floor 5 Most Healing": "dungeons_catacombs_floor_5_most_healing",
    "Collection Sapling:5": "collection_sapling:5",
    "Kills Spirit Bull": "kills_spirit_bull",
    "Deaths Kill Fire": "deaths_kill_fire",
    "Kills Crypt Undead Relenter": "kills_crypt_undead_relenter",
    "Kills Sea Witch": "kills_sea_witch",
    "Collection Clay": "collection_clay",
    "Deaths Rabbit": "deaths_rabbit",
    "Collection Tightly Tied Hay Bale": "collection_tightly_tied_hay_bale",
    "Gifts Given": "gifts_given",
    "Dungeons Catacombs Floor 3 Completions": "dungeons_catacombs_floor_3_completions",
    "Deaths Sadan Giant": "deaths_sadan_giant",
    "Deaths Magma Cube": "deaths_magma_cube",
    "Dungeons Catacombs Floor 7 Best Score": "dungeons_catacombs_floor_7_best_score",
    "Dungeons Catacombs Entrance Mobs Killed": "dungeons_catacombs_entrance_mobs_killed",
    "Kills Crypt Undead Chilynn": "kills_crypt_undead_chilynn",
    "Blaze Rod Collection": "collection_blaze_rod",
    "Dungeons Catacombs Entrance Most Damage Archer": "dungeons_catacombs_entrance_most_damage_archer",
    "Kills Cave Spider": "kills_cave_spider",
    "Kills Skeletor": "kills_skeletor",
    "Highest Critical Damage": "highest_critical_damage",
    "Deaths Crypt Undead Adamwho": "deaths_crypt_undead_adamwho",
    "Deaths Crypt Undead Revengeee": "deaths_crypt_undead_revengeee",
    "Kills Runic": "kills_runic",
    "Spider Slayer Xp": "spider_slayer_xp",
    "Kills Corrupted Protector": "kills_corrupted_protector",
    "Dungeons Catacombs Floor 3 Most Damage Mage": "dungeons_catacombs_floor_3_most_damage_mage",
    "Dungeon Hub Precursor Ruins No Abilities With Return Best Time": "dungeon_hub_precursor_ruins_no_abilities_with_return_best_time",
    "Cobblestone Collection": "collection_cobblestone",
    "Dungeons Catacombs Floor 4 Most Damage Tank": "dungeons_catacombs_floor_4_most_damage_tank",
    "Collection Red Rose:2": "collection_red_rose:2",
    "Dungeons Catacombs Floor 7 Mobs Killed": "dungeons_catacombs_floor_7_mobs_killed",
    "Carrot Collection": "collection_carrot_item",
    "Kills Crypt Undead Donpireso": "kills_crypt_undead_donpireso",
    "Kills Crypt Undead Jayavarmen": "kills_crypt_undead_jayavarmen",
    "Kills Night Squid": "kills_night_squid",
    "Dungeons Catacombs Floor 5 Fastest Time S+": "dungeons_catacombs_floor_5_fastest_time_s+",
    "Deaths 1": "deaths_1",
    "Collection Red Rose:4": "collection_red_rose:4",
    "Dungeons Catacombs Floor 6 Most Damage Healer": "dungeons_catacombs_floor_6_most_damage_healer",
    "Kills Revenant Horror Tier 3": "zombie_slayer_boss_kills_tier_2",
    "Deaths Zombie Soldier": "deaths_zombie_soldier",
    "Skill Enchanting Xp": "skill_enchanting_xp",
    "Deaths Necron Guard": "deaths_necron_guard",
    "Deaths Wither Gourd": "deaths_wither_gourd",
    "Deaths Crypt Undead Apunch": "deaths_crypt_undead_apunch",
    "Kills Old Wolf": "kills_old_wolf",
    "Auctions Sold Common": "auctions_sold_common",
    "Auctions Fees": "auctions_fees",
    "Auctions Gold Spent": "auctions_gold_spent",
    "Dungeons Catacombs Floor 1 Most Damage Tank": "dungeons_catacombs_floor_1_most_damage_tank",
    "Kills Strong Dragon": "kills_strong_dragon",
    "Kills Deep Sea Golem": "kills_deep_sea_golem",
    "Deaths Night Respawning Skeleton": "deaths_night_respawning_skeleton",
    "Minion Slime Kills": "kills_generator_slime",
    "Dungeons Catacombs Floor 3 Most Damage Berserk": "dungeons_catacombs_floor_3_most_damage_berserk",
    "Deaths Mimic": "deaths_mimic",
    "Deaths Alpha Wolf": "deaths_alpha_wolf",
    "Mythos Burrows Dug Next Epic": "mythos_burrows_dug_next_EPIC",
    "Skill Combat Xp": "skill_combat_xp",
    "Kills Carrot King": "kills_carrot_king",
    "Kills Siamese Lynx": "kills_siamese_lynx",
    "Collection Packed Ice": "collection_packed_ice",
    "Dungeons Catacombs Floor 4 Most Mobs Killed": "dungeons_catacombs_floor_4_most_mobs_killed",
    "Sugar Cane Collection": "collection_sugar_cane",
    "Kills Ancient One": "kills_ancient_one",
    "Kills Crypt Undead Likaos": "kills_crypt_undead_likaos",
    "Deaths Pigman": "deaths_pigman",
    "Deaths Crypt Undead Dctr": "deaths_crypt_undead_dctr",
    "Collection Snow Block": "collection_snow_block",
    "Deaths Catfish": "deaths_catfish",
    "Kills Jockey Shot Silverfish": "kills_jockey_shot_silverfish",
    "Kills Crypt Undead Nicholas": "kills_crypt_undead_nicholas",
    "Kills Crypt Undead Pjoke1": "kills_crypt_undead_pjoke1",
    "Spruce Wood Collection": "collection_log:1",
    "Deaths Spirit Wolf": "deaths_spirit_wolf",
    "Deaths Trap": "deaths_trap",
    "Kills Tarantula Broodfather Tier 3": "spider_slayer_boss_kills_tier_2",
    "Deaths Skeleton Lord": "deaths_skeleton_lord",
    "Deaths Bat": "deaths_bat",
    "Dungeons Catacombs Floor 3 Watcher Kills": "dungeons_catacombs_floor_3_watcher_kills",
    "Deaths Professor Archer Guardian": "deaths_professor_archer_guardian",
    "Kills Crypt Undead Minikloon": "kills_crypt_undead_minikloon",
    "Kills Obsidian Wither": "kills_obsidian_wither",
    "Deaths Wraith": "deaths_wraith",
    "Kills Crypt Undead Codename B": "kills_crypt_undead_codename_b",
    "Gravel Collection": "collection_gravel",
    "Kills Spirit Wolf": "kills_spirit_wolf",
    "Deaths Tiger Shark": "deaths_tiger_shark",
    "Deaths Watcher Guardian": "deaths_watcher_guardian",
    "Rotten Flesh Collection": "collection_rotten_flesh",
    "Deaths Sniper Skeleton": "deaths_sniper_skeleton",
    "Deaths Crypt Undead Connorlinfoot": "deaths_crypt_undead_connorlinfoot",
    "Deaths Crypt Undead Agentk": "deaths_crypt_undead_agentk",
    "Kills Sheep": "kills_sheep",
    "Kills Zombie": "kills_zombie",
    "Kills Dungeon Respawning Skeleton": "kills_dungeon_respawning_skeleton",
    "Deaths Watcher Giant Boulder": "deaths_watcher_giant_boulder",
    "Kills Revenant Horror Tier 1": "zombie_slayer_boss_kills_tier_0",
    "Dungeons Catacombs Entrance Most Mobs Killed": "dungeons_catacombs_entrance_most_mobs_killed",
    "Mythos Burrows Dug Combat Rare": "mythos_burrows_dug_combat_RARE",
    "Dungeons Catacombs Floor 4 Fastest Time S": "dungeons_catacombs_floor_4_fastest_time_s",
    "Deaths Horse": "deaths_horse",
    "Mythos Burrows Chains Complete Rare": "mythos_burrows_chains_complete_RARE",
    "Kills Goblin Murderlover": "kills_goblin_murderlover",
    "Deaths Crypt Undead Ladybleu": "deaths_crypt_undead_ladybleu",
    "Gold Ingot Collection": "collection_gold_ingot",
    "Skill Alchemy Xp": "skill_alchemy_xp",
    "Deaths Sea Archer": "deaths_sea_archer",
    "Kills Alpha Wolf": "kills_alpha_wolf",
    "Skill Foraging Xp": "skill_foraging_xp",
    "Kills Crypt Undead Valentin": "kills_crypt_undead_valentin",
    "Auctions Bought Legendary": "auctions_bought_legendary",
    "Kills Wither Miner": "kills_wither_miner",
    "Kills Skeleton Emperor": "kills_skeleton_emperor",
    "Kills Jockey Skeleton": "kills_jockey_skeleton",
    "Kills Zombie Deep": "kills_zombie_deep",
    "Dungeons Catacombs Floor 1 Most Mobs Killed": "dungeons_catacombs_floor_1_most_mobs_killed",
    "Kills Pack Spirit": "kills_pack_spirit",
    "Deaths Crypt Undead Rezzus": "deaths_crypt_undead_rezzus",
    "Dungeons Catacombs Floor 7 Fastest Time S+": "dungeons_catacombs_floor_7_fastest_time_s+",
    "Dungeons Catacombs Floor 5 Fastest Time S": "dungeons_catacombs_floor_5_fastest_time_s",
    "Kills Crypt Undead Judg3": "kills_crypt_undead_judg3",
    "Collection Mutant Nether Stalk": "collection_mutant_nether_stalk",
    "Kills Tarantula Spider": "kills_tarantula_spider",
    "Kills Spider": "kills_spider",
    "Deaths Scared Skeleton": "deaths_scared_skeleton",
    "Kills Splitter Spider": "kills_splitter_spider",
    "Dungeons Catacombs Floor 2 Most Mobs Killed": "dungeons_catacombs_floor_2_most_mobs_killed",
    "Kills Nightmare": "kills_nightmare",
    "Kills Young Dragon": "kills_young_dragon",
    "Deaths Crypt Undead Jayavarmen": "deaths_crypt_undead_jayavarmen",
    "Kills Bat Pinata": "kills_bat_pinata",
    "Dungeon Hub Giant Mushroom No Abilities With Return Best Time": "dungeon_hub_giant_mushroom_no_abilities_with_return_best_time",
    "Kills Forest Island Bat": "kills_forest_island_bat",
    "Deaths Goblin Creeper": "deaths_goblin_creeper",
    "Dungeon Hub Crystal Core Nothing With Return Best Time": "dungeon_hub_crystal_core_nothing_with_return_best_time",
    "Deaths Crypt Undead Erosemberg": "deaths_crypt_undead_erosemberg",
    "Deaths Blue Shark": "deaths_blue_shark",
    "Deaths Crypt Undead Robitybobity": "deaths_crypt_undead_robitybobity",
    "Kills Skeletor Prime": "kills_skeletor_prime",
    "Deaths Ice Walker": "deaths_ice_walker",
    "Kills Caverns Ghost": "kills_caverns_ghost",
    "Auctions Sold Special": "auctions_sold_special",
    "Deaths Respawning Skeleton": "deaths_respawning_skeleton",
    "Auctions Bought Special": "auctions_bought_special",
    "Kills Wise Dragon": "kills_wise_dragon",
    "Kills Crypt Undead Rezzus": "kills_crypt_undead_rezzus",
    "Kills Endermite": "kills_endermite",
    "Deaths Horseman Zombie": "deaths_horseman_zombie",
    "Deaths Sea Walker": "deaths_sea_walker",
    "Deaths Deathmite": "deaths_deathmite",
    "Kills Diamond Zombie": "kills_diamond_zombie",
    "Dungeons Catacombs Floor 5 Most Damage Archer": "dungeons_catacombs_floor_5_most_damage_archer",
    "Deaths Void": "deaths_void",
    "Deaths Tarantula Spider": "deaths_tarantula_spider",
    "Fairy Souls": "fairy_souls",
    "Deaths Zombie Deep": "deaths_zombie_deep",
    "Dungeon Hub Precursor Ruins Anything With Return Best Time": "dungeon_hub_precursor_ruins_anything_with_return_best_time",
    "Deaths Weaver Spider": "deaths_weaver_spider",
    "Brood Mother Deaths": "deaths_brood_mother_spider",
    "Dungeon Hub Precursor Ruins Nothing With Return Best Time": "dungeon_hub_precursor_ruins_nothing_with_return_best_time",
    "Deaths Crypt Undead Pieter": "deaths_crypt_undead_pieter",
    "Auctions Sold Rare": "auctions_sold_rare",
    "Kills Random Slime": "kills_random_slime",
    "Deaths Skeletor": "deaths_skeletor",
    "Auctions Bids": "auctions_bids",
    "Items Fished Large Treasure": "items_fished_large_treasure",
    "Collection Gold Ore": "collection_gold_ore",
    "Deaths Old Wolf": "deaths_old_wolf",
    "Deaths Crypt Undead Jamiethegeek": "deaths_crypt_undead_jamiethegeek",
    "Kills Sea Guardian": "kills_sea_guardian",
    "Kills Mayor Jerry Blue": "kills_mayor_jerry_blue",
    "Kills Crypt Undead Bloozing": "kills_crypt_undead_bloozing",
    "Deaths Dasher Spider": "deaths_dasher_spider",
    "Deaths Crypt Undead Flameboy101": "deaths_crypt_undead_flameboy101",
    "Dungeons Catacombs Floor 6 Most Damage Tank": "dungeons_catacombs_floor_6_most_damage_tank",
    "Deaths Scarecrow": "deaths_scarecrow",
    "Collection Slime Block": "collection_slime_block",
    "Deaths Maxor": "deaths_maxor",
    "Deaths Gaia Construct": "deaths_gaia_construct",
    "Deaths Creeper": "deaths_creeper",
    "Seeds Collection": "collection_seeds",
    "Deaths Minos Inquisitor": "deaths_minos_inquisitor",
    "Kills Fireball Magma Cube": "kills_fireball_magma_cube",
    "Dungeons Catacombs Floor 4 Most Damage Healer": "dungeons_catacombs_floor_4_most_damage_healer",
    "Kills Cow": "kills_cow",
    "Deaths Protector Dragon": "deaths_protector_dragon",
    "Kills Guardian Defender": "kills_guardian_defender",
    "Kills Scarecrow": "kills_scarecrow",
    "Kills Liquid Hot Magma": "kills_liquid_hot_magma",
    "Kills Goblin Knife Thrower": "kills_goblin_knife_thrower",
    "Kills Super Tank Zombie": "kills_super_tank_zombie",
    "Dungeons Catacombs Floor 6 Most Damage Mage": "dungeons_catacombs_floor_6_most_damage_mage",
    "Collection Double Plant:5": "collection_double_plant:5",
    "Dungeons Catacombs Floor 2 Fastest Time S": "dungeons_catacombs_floor_2_fastest_time_s",
    "Deaths Crypt Witherskeleton": "deaths_crypt_witherskeleton",
    "Dungeons Catacombs Floor 4 Times Played": "dungeons_catacombs_floor_4_times_played",
    "Kills Soul Of The Alpha": "kills_soul_of_the_alpha",
    "Kills Skeleton Lord": "kills_skeleton_lord",
    "Kills Crypt Undead Pieter": "kills_crypt_undead_pieter",
    "Kills Crypt Lurker": "kills_crypt_lurker",
    "Deaths Bonzo": "deaths_bonzo",
    "Deaths Crypt Undead Luckykessie": "deaths_crypt_undead_luckykessie",
    "Kills Tarantula Broodfather Tier 1": "spider_slayer_boss_kills_tier_0",
    "Collection Red Rose:1": "collection_red_rose:1",
    "Deaths Fall": "deaths_fall",
    "Dungeons Catacombs Floor 5 Most Damage Mage": "dungeons_catacombs_floor_5_most_damage_mage",
    "Potato Collection": "collection_potato_item",
    "Collection Red Rose": "collection_red_rose",
    "Jungle Wood Collection": "collection_log:3",
    "Kills Crypt Undead Apunch": "kills_crypt_undead_apunch",
    "Collection Egg": "collection_egg",
    "Deaths Crypt Undead Valentin": "deaths_crypt_undead_valentin",
    "Dungeons Catacombs Floor 7 Most Damage Mage": "dungeons_catacombs_floor_7_most_damage_mage",
    "Deaths Goblin Golem": "deaths_goblin_golem",
    "Deaths Zombie Knight": "deaths_zombie_knight",
    "Dungeons Catacombs Floor 3 Most Damage Archer": "dungeons_catacombs_floor_3_most_damage_archer",
    "Mythos Burrows Dug Combat Uncommon": "mythos_burrows_dug_combat_UNCOMMON",
    "Deaths Crypt Undead Codename B": "deaths_crypt_undead_codename_b",
    "Most Winter Snowballs Hit": "most_winter_snowballs_hit",
    "Dungeons Catacombs Floor 3 Fastest Time": "dungeons_catacombs_floor_3_fastest_time",
    "Deaths Skeleton Soldier": "deaths_skeleton_soldier",
    "Deaths Crystal Sentry": "deaths_crystal_sentry",
    "Deaths Minos Champion": "deaths_minos_champion",
    "Minion Slime Deaths": "deaths_generator_slime",
    "Dungeons Catacombs Entrance Times Played": "dungeons_catacombs_entrance_times_played",
    "Kills Minos Hunter": "kills_minos_hunter",
    "Nether Wart Collection": "collection_nether_stalk",
    "Collection Snow Ball": "collection_snow_ball",
    "Kills Crypt Tank Zombie": "kills_crypt_tank_zombie",
    "Brood Mother Kills": "kills_brood_mother_spider",
    "Dungeons Catacombs Entrance Most Damage Mage": "dungeons_catacombs_entrance_most_damage_mage",
    "Mythos Burrows Dug Next Uncommon": "mythos_burrows_dug_next_UNCOMMON",
    "Kills Headless Horseman": "kills_headless_horseman",
    "Deaths Sadan Golem": "deaths_sadan_golem",
    "Dungeons Catacombs Entrance Completions": "dungeons_catacombs_entrance_completions",
    "Kills Deathmite": "kills_deathmite",
    "Dungeons Catacombs Entrance Watcher Kills": "dungeons_catacombs_entrance_watcher_kills",
    "Kills Splitter Spider Silverfish": "kills_splitter_spider_silverfish",
    "Deaths Liquid Hot Magma": "deaths_liquid_hot_magma",
    "Deaths Yeti": "deaths_yeti",
    "Kills Chicken": "kills_chicken",
    "Kills Ghast": "kills_ghast",
    "Deaths Goblin Weakling Bow": "deaths_goblin_weakling_bow",
    "Ender Pearl Collection": "collection_ender_pearl",
    "Mythos Burrows Chains Complete Epic": "mythos_burrows_chains_complete_EPIC",
    "Dungeon Hub Crystal Core Anything No Return Best Time": "dungeon_hub_crystal_core_anything_no_return_best_time",
    "Dungeons Catacombs Entrance Best Score": "dungeons_catacombs_entrance_best_score",
    "Kills Sea Emperor": "kills_sea_emperor",
    "Auctions Bought Uncommon": "auctions_bought_uncommon",
    "Deaths Goblin Knife Thrower": "deaths_goblin_knife_thrower",
    "Deaths Witch Bat": "deaths_witch_bat",
    "Kills Sadan Statue": "kills_sadan_statue",
    "Ender Crystals Destroyed": "ender_crystals_destroyed",
    "Dungeons Catacombs Floor 5 Completions": "dungeons_catacombs_floor_5_completions",
    "Deaths Crypt Dreadlord": "deaths_crypt_dreadlord",
    "Kills Wither Skeleton": "kills_wither_skeleton",
    "Dungeons Catacombs Floor 7 Most Damage Tank": "dungeons_catacombs_floor_7_most_damage_tank",
    "Mythos Burrows Dug Treasure Rare": "mythos_burrows_dug_treasure_RARE",
    "Deaths Nightmare": "deaths_nightmare",
    "Kills Spirit Rabbit": "kills_spirit_rabbit",
    "Dungeons Catacombs Floor 5 Most Damage Tank": "dungeons_catacombs_floor_5_most_damage_tank",
    "Kills Bonzo Summon Undead": "kills_bonzo_summon_undead",
    "Deaths Crypt Tank Zombie": "deaths_crypt_tank_zombie",
    "Deaths Unknown": "deaths_unknown",
    "Raw Rabbit Collection": "collection_rabbit",
    "Kills Crypt Undead Plancke": "kills_crypt_undead_plancke",
    "Deaths Grinch": "deaths_grinch",
    "Dungeons Catacombs Floor 3 Times Played": "dungeons_catacombs_floor_3_times_played",
    "Collection Double Plant": "collection_double_plant",
    "Items Fished Treasure": "items_fished_treasure",
    "Kills Enderman": "kills_enderman",
    "Kills Pond Squid": "kills_pond_squid",
    "Kills Mayor Jerry Golden": "kills_mayor_jerry_golden",
    "Kills Dungeon Respawning Skeleton Skull": "kills_dungeon_respawning_skeleton_skull",
    "Collection Raw Beef": "collection_raw_beef",
    "Collection Emerald Block": "collection_emerald_block",
    "Collection Redstone Block": "collection_redstone_block",
    "Collection Rabbit Foot": "collection_rabbit_foot",
    "Kills Goblin Golem": "kills_goblin_golem",
    "String Collection": "collection_string",
    "Deaths Sea Guardian": "deaths_sea_guardian",
    "Deaths Corrupted Protector": "deaths_corrupted_protector",
    "Dungeons Catacombs Floor 1 Watcher Kills": "dungeons_catacombs_floor_1_watcher_kills",
    "Deaths Crypt Undead Cecer": "deaths_crypt_undead_cecer",
    "Collection Iron Ore": "collection_iron_ore",
    "Deaths Diamond Zombie": "deaths_diamond_zombie",
    "Collection Double Plant:4": "collection_double_plant:4",
    "Deaths Spirit Rabbit": "deaths_spirit_rabbit",
    "Pet Milestone Ores Mined": "pet_milestone_ores_mined",
    "Raw Fish Collection": "collection_raw_fish",
    "Kills Werewolf": "kills_werewolf",
    "Deaths Howling Spirit": "deaths_howling_spirit",
    "Dungeon Hub Crystal Core No Abilities No Return Best Time": "dungeon_hub_crystal_core_no_abilities_no_return_best_time",
    "Kills Crystal Sentry": "kills_crystal_sentry",
    "Oak Wood Collection": "collection_log",
    "Kills Skeleton": "kills_skeleton",
    "Collection Double Plant:1": "collection_double_plant:1",
    "Kills Watcher Bonzo": "kills_watcher_bonzo",
    "Kills Goblin Weakling Bow": "kills_goblin_weakling_bow",
    "Auctions Bought Epic": "auctions_bought_epic",
    "Wolf Slayer Xp": "wolf_slayer_xp",
    "Dungeons Catacombs Floor 6 Completions": "dungeons_catacombs_floor_6_completions",
    "Deaths Scarf Mage": "deaths_scarf_mage",
    "Collection Gold Block": "collection_gold_block",
    "Pet Milestone Sea Creatures Killed": "pet_milestone_sea_creatures_killed",
    "Deaths Fall Kill": "deaths_fall_kill",
    "Kills Sven Packmaster Tier 3": "wolf_slayer_boss_kills_tier_2",
    "Dungeons Catacombs Floor 4 Fastest Time": "dungeons_catacombs_floor_4_fastest_time",
    "Deaths Cave Spider": "deaths_cave_spider",
    "Kills Crypt Undead Hypixel": "kills_crypt_undead_hypixel",
    "Dungeons Catacombs Entrance Fastest Time S": "dungeons_catacombs_entrance_fastest_time_s",
    "Collection Lapis Block": "collection_lapis_block",
    "Wheat Collection": "collection_wheat",
    "Ice Collection": "collection_ice",
    "Auctions Sold Uncommon": "auctions_sold_uncommon",
    "Kills Crypt Undead Cecer": "kills_crypt_undead_cecer",
    "Dungeons Catacombs Floor 7 Watcher Kills": "dungeons_catacombs_floor_7_watcher_kills",
    "Deaths Dungeon Respawning Skeleton Skull": "deaths_dungeon_respawning_skeleton_skull",
    "Kills Sniper Skeleton": "kills_sniper_skeleton",
    "Kills Sadan Golem": "kills_sadan_golem",
    "Kills Shadow Assassin": "kills_shadow_assassin",
    "Collection Brick": "collection_brick",
    "Collection Iron Block": "collection_iron_block",
    "Mythos Burrows Dug Combat Epic": "mythos_burrows_dug_combat_EPIC",
    "Highest Crit Damage": "highest_crit_damage",
    "Kills Minotaur": "kills_minotaur",
    "Minion Ghast Kills": "kills_generator_ghast",
    "Deaths Runic Zombie": "deaths_runic_zombie",
    "Deaths Skeleton Emperor": "deaths_skeleton_emperor",
    "Items Fished": "items_fished",
    "Dungeons Catacombs Floor 1 Most Damage Archer": "dungeons_catacombs_floor_1_most_damage_archer",
    "Zealot Deaths": "deaths_zealot_enderman",
    "Minion Magma Cube Deaths": "deaths_generator_magma_cube",
    "Kills Crypt Undead Williamtiger": "kills_crypt_undead_williamtiger",
    "Kills Guardian Boss": "kills_guardian_boss",
    "Deaths Armor Stand": "deaths_armor_stand",
    "Deaths Cow": "deaths_cow",
    "Deaths Watcher Bonzo": "deaths_watcher_bonzo",
    "Deaths Siamese Lynx": "deaths_siamese_lynx",
    "Deaths Crypt Undead Donpireso": "deaths_crypt_undead_donpireso",
    "Magma Cream Collection": "collection_magma_cream",
    "Deaths Skeleton Master": "deaths_skeleton_master",
    "Kills Powder Ghast": "kills_powder_ghast",
    "Kills Trick Or Treater": "kills_trick_or_treater",
    "Deaths Frosty The Snowman": "deaths_frosty_the_snowman",
    "Deaths Caverns Ghost": "deaths_caverns_ghost",
    "Acacia Wood Collection": "collection_log_2",
    "Kills Goblin Creepertamer": "kills_goblin_creepertamer",
    "Kills Crypt Undead Flameboy101": "kills_crypt_undead_flameboy101",
    "Mythos Burrows Dug Next Null": "mythos_burrows_dug_next_null",
    "Deaths Carrot King": "deaths_carrot_king",
    "Dungeons Catacombs Floor 1 Fastest Time S": "dungeons_catacombs_floor_1_fastest_time_s",
    "Kills Crypt Undead Jamiethegeek": "kills_crypt_undead_jamiethegeek",
    "Kills Phantom Fisherman": "kills_phantom_fisherman",
    "Kills Mayor Jerry Purple": "kills_mayor_jerry_purple",
    "Kills Pack Wolf": "kills_pack_wolf",
    "Kills Witch Bat": "kills_witch_bat",
    "Kills Crypt Souleater": "kills_crypt_souleater",
    "Mythos Burrows Dug Combat Legendary": "mythos_burrows_dug_combat_LEGENDARY",
    "Kills Yeti": "kills_yeti",
    "Diamond Collection": "collection_diamond",
    "Deaths Wither Guard": "deaths_wither_guard",
    "Deaths Sadan Statue": "deaths_sadan_statue",
    "Dungeons Catacombs Floor 4 Watcher Kills": "dungeons_catacombs_floor_4_watcher_kills",
    "Coal Collection": "collection_coal",
    "Dungeons Catacombs Floor 7 Fastest Time": "dungeons_catacombs_floor_7_fastest_time",
    "Kills Deep Sea Protector": "kills_deep_sea_protector",
    "Deaths Lapis Zombie": "deaths_lapis_zombie",
    "Dungeons Catacombs Floor 3 Most Damage Healer": "dungeons_catacombs_floor_3_most_damage_healer",
    "Deaths Horseman Horse": "deaths_horseman_horse",
    "Raw Salmon Collection": "collection_raw_fish:1",
    "Total Fishing Actions": "total_fishing_actions",
    "Kills Parasite": "kills_parasite",
    "Dungeons Catacombs Floor 5 Most Damage Healer": "dungeons_catacombs_floor_5_most_damage_healer",
    "Birch Wood Collection": "collection_log:2",
    "Kills Sven Packmaster Tier 2": "wolf_slayer_boss_kills_tier_1",
    "Kills Wither Guard": "kills_wither_guard",
    "Kills Watcher": "kills_watcher",
    "Kills Treasure Hoarder": "kills_treasure_hoarder",
    "Deaths Crypt Souleater": "deaths_crypt_souleater",
    "Total Dragon Deaths": "total_dragon_deaths",
    "Most Winter Magma Damage Dealt": "most_winter_magma_damage_dealt",
    "Mythos Burrows Dug Next Common": "mythos_burrows_dug_next_COMMON",
    "Dungeon Hub Crystal Core No Pearls With Return Best Time": "dungeon_hub_crystal_core_no_pearls_with_return_best_time",
    "Kills Scarf Mage": "kills_scarf_mage",
    "Kills Minos Champion": "kills_minos_champion",
    "Dungeons Berserk Xp": "dungeons_berserk_xp",
    "Deaths Crypt Undead Friedrich": "deaths_crypt_undead_friedrich",
    "Kills Grinch": "kills_grinch",
    "Collection Poisonous Potato": "collection_poisonous_potato",
    "Kills Scary Jerry": "kills_scary_jerry",
    "Deaths Crypt Undead Williamtiger": "deaths_crypt_undead_williamtiger",
    "Kills Ice Walker": "kills_ice_walker",
    "Total Slayer Boss Kills": "total_slayer_boss_kills",
    "Kills Dungeon Secret Bat": "kills_dungeon_secret_bat",
    "Kills Watcher Livid": "kills_watcher_livid",
    "Deaths Zombie Commander": "deaths_zombie_commander",
    "Gifts Received": "gifts_received",
    "Kills Crypt Undead Erosemberg": "kills_crypt_undead_erosemberg",
    "Mythos Burrows Dug Combat Common": "mythos_burrows_dug_combat_COMMON",
    "Deaths Wolf": "deaths_wolf",
    "Kills": "kills",
    "Deaths Cactus": "deaths_cactus",
    "Kills Sadan Giant": "kills_sadan_giant",
    "Kills Respawning Skeleton": "kills_respawning_skeleton",
    "Kills Batty Witch": "kills_batty_witch",
    "Mythos Burrows Dug Treasure Null": "mythos_burrows_dug_treasure_null",
    "Obsidian Collection": "collection_obsidian",
    "Kills Blue Shark": "kills_blue_shark",
    "Dungeons Catacombs Floor 7 Completions": "dungeons_catacombs_floor_7_completions",
    "Kills Superior Dragon": "kills_superior_dragon",
    "Auctions Sold Mythic": "auctions_sold_mythic",
    "Deaths Sea Witch": "deaths_sea_witch",
    "Deaths Tentaclees": "deaths_tentaclees",
    "End Stone Collection": "collection_ender_stone",
    "Deaths Old Dragon": "deaths_old_dragon",
    "Dungeon Hub Giant Mushroom Nothing No Return Best Time": "dungeon_hub_giant_mushroom_nothing_no_return_best_time",
    "Deaths Phantom Spirit": "deaths_phantom_spirit",
    "Deaths Minos Hunter": "deaths_minos_hunter",
    "Kills Protector Dragon": "kills_protector_dragon",
    "Mythos Burrows Chains Complete Null": "mythos_burrows_chains_complete_null",
    "Kills Revenant Horror Tier 2": "zombie_slayer_boss_kills_tier_1",
    "Deaths Crypt Undead  Fudgiethewhale": "deaths_crypt_undead__fudgiethewhale",
    "Deaths Watcher Livid": "deaths_watcher_livid",
    "Deaths King Midas": "deaths_king_midas",
    "Collection Stone": "collection_stone",
    "Kills Crypt Undead Dctr": "kills_crypt_undead_dctr",
    "Dungeons Catacombs Floor 2 Most Damage Berserk": "dungeons_catacombs_floor_2_most_damage_berserk",
    "Dungeons Catacombs Floor 4 Completions": "dungeons_catacombs_floor_4_completions",
    "Auctions Highest Bid": "auctions_highest_bid",
    "Collection Wool": "collection_wool",
    "Pet Score": "pet_score",
    "Glowstone Collection": "collection_glowstone_dust",
    "Pumpkin Collection": "collection_pumpkin",
    "Dungeons Catacombs Floor 1 Fastest Time": "dungeons_catacombs_floor_1_fastest_time",
    "Deaths Zombie": "deaths_zombie",
    "Collection Polished Pumpkin": "collection_polished_pumpkin",
    "Kills Rabbit": "kills_rabbit",
    "Kills Water Hydra": "kills_water_hydra",
    "Dungeon Hub Giant Mushroom Nothing With Return Best Time": "dungeon_hub_giant_mushroom_nothing_with_return_best_time",
    "Mithril Collection": "collection_mithril_ore",
    "Dungeons Catacombs Floor 2 Completions": "dungeons_catacombs_floor_2_completions",
    "Total Skill Xp": "total_skill_xp",
    "Dungeons Catacombs Floor 4 Most Damage Archer": "dungeons_catacombs_floor_4_most_damage_archer",
    "Mythos Burrows Chains Complete Uncommon": "mythos_burrows_chains_complete_UNCOMMON",
    "Pumpkin Launcher Count": "pumpkin_launcher_count",
    "Dungeons Archer Xp": "dungeons_archer_xp",
    "Deaths Emerald Slime": "deaths_emerald_slime",
    "Foraging Race Best Time": "foraging_race_best_time",
    "Deaths Crypt Undead Marius": "deaths_crypt_undead_marius",
    "Deaths Phantom Fisherman": "deaths_phantom_fisherman",
    "Dungeons Catacombs Floor 5 Best Score": "dungeons_catacombs_floor_5_best_score",
    "Deaths Unstable Dragon": "deaths_unstable_dragon",
    "Auctions Sold Epic": "auctions_sold_epic",
    "Dungeons Catacombs Floor 7 Most Damage Berserk": "dungeons_catacombs_floor_7_most_damage_berserk",
    "Deaths Wise Dragon": "deaths_wise_dragon",
    "Kills Necron Guard": "kills_necron_guard",
    "Kills Zombie Lord": "kills_zombie_lord",
    "Dungeons Catacombs Floor 2 Mobs Killed": "dungeons_catacombs_floor_2_mobs_killed",
    "Kills Silverfish": "kills_silverfish",
    "Chicken Race Best Time 2": "chicken_race_best_time_2",
    "Deaths Crypt Undead Nicholas": "deaths_crypt_undead_nicholas",
    "Deaths Professor Guardian Summon": "deaths_professor_guardian_summon",
    "Clay Collection": "collection_clay_ball",
    "Kills Mayor Jerry Green": "kills_mayor_jerry_green",
    "Deaths Watcher Giant Bigfoot": "deaths_watcher_giant_bigfoot",
    "Kills Goblin Creeper": "kills_goblin_creeper",
    "Dungeons Catacombs Floor 3 Best Score": "dungeons_catacombs_floor_3_best_score",
    "Deaths Horseman Bat": "deaths_horseman_bat",
    "Dungeons Catacombs Xp": "dungeons_catacombs_xp",
    "Cocoa Beans Collection": "collection_ink_sack:3",
    "Dungeons Catacombs Floor 1 Best Score": "dungeons_catacombs_floor_1_best_score",
    "Sand Collection": "collection_sand",
    "Kills Super Archer": "kills_super_archer",
    "Kills Crypt Undead Alexander": "kills_crypt_undead_alexander",
    "Deaths Crushed": "deaths_crushed",
    "Dungeons Mage Xp": "dungeons_mage_xp",
    "Kills Zombie Villager": "kills_zombie_villager",
    "Dungeons Catacombs Floor 5 Mobs Killed": "dungeons_catacombs_floor_5_mobs_killed",
    "Deaths Crypt Undead Nitroholic ": "deaths_crypt_undead_nitroholic_",
    "Zombie Slayer Xp": "zombie_slayer_xp",
    "Deaths Pig Zombie": "deaths_pig_zombie",
    "Kills Great White Shark": "kills_great_white_shark",
    "Deaths Spirit Bat": "deaths_spirit_bat",
    "Kills Revenant Zombie": "kills_revenant_zombie",
    "Deaths Blaze": "deaths_blaze",
    "Dungeons Catacombs Floor 6 Most Damage Archer": "dungeons_catacombs_floor_6_most_damage_archer",
    "Deaths Professor Warrior Guardian": "deaths_professor_warrior_guardian",
    "Kills Crypt Dreadlord": "kills_crypt_dreadlord",
    "Deaths Trick Or Treater": "deaths_trick_or_treater",
    "Raw Chicken Collection": "collection_raw_chicken",
    "Deaths Zombie Lord": "deaths_zombie_lord",
    "Kills Sven Packmaster Tier 1": "wolf_slayer_boss_kills_tier_0",
    "Deaths Crypt Undead Sylent": "deaths_crypt_undead_sylent",
    "Deaths Iron Golem": "deaths_iron_golem",
    "Dungeon Hub Giant Mushroom Anything With Return Best Time": "dungeon_hub_giant_mushroom_anything_with_return_best_time",
    "Kills Scarf Priest": "kills_scarf_priest",
    "Deaths Fire": "deaths_fire",
    "Kills Blaze Higher Or Lower": "kills_blaze_higher_or_lower",
    "Deaths Goblin Weakling Melee": "deaths_goblin_weakling_melee",
    "Dungeons Catacombs Floor 2 Fastest Time": "dungeons_catacombs_floor_2_fastest_time",
    "Kills Dasher Spider": "kills_dasher_spider",
    "Deaths Dungeon Respawning Skeleton": "deaths_dungeon_respawning_skeleton",
    "Dungeons Catacombs Floor 6 Fastest Time": "dungeons_catacombs_floor_6_fastest_time",
    "Deaths Crypt Undead Sfarnham": "deaths_crypt_undead_sfarnham",
    "Deaths Random Slime": "deaths_random_slime",
    "Dungeons Healer Xp": "dungeons_healer_xp",
    "Mythos Burrows Dug Treasure Legendary": "mythos_burrows_dug_treasure_LEGENDARY",
    "Kills Crypt Undead Marius": "kills_crypt_undead_marius",
    "Deaths Deep Sea Protector": "deaths_deep_sea_protector",
    "Kills Crypt Undead Sfarnham": "kills_crypt_undead_sfarnham",
    "Kills Diamond Skeleton": "kills_diamond_skeleton",
    "Dungeons Catacombs Floor 1 Most Damage Mage": "dungeons_catacombs_floor_1_most_damage_mage",
    "Dungeons Catacombs Floor 6 Fastest Time S": "dungeons_catacombs_floor_6_fastest_time_s",
    "Mythos Burrows Dug Combat": "mythos_burrows_dug_combat",
    "Kills Voracious Spider": "kills_voracious_spider",
    "Dungeons Catacombs Floor 1 Most Damage Healer": "dungeons_catacombs_floor_1_most_damage_healer",
    "Collection Yellow Flower": "collection_yellow_flower",
    "Kills Crypt Undead Bernhard": "kills_crypt_undead_bernhard",
    "Deaths Crypt Undead Relenter": "deaths_crypt_undead_relenter",
    "Deaths Brood Mother Cave Spider": "deaths_brood_mother_cave_spider",
    "Deaths Monster Of The Deep": "deaths_monster_of_the_deep",
    "Emerald Collection": "collection_emerald",
    "Kills Crypt Undead Christian": "kills_crypt_undead_christian",
    "Items Fished Normal": "items_fished_normal",
    "Cactus Collection": "collection_cactus",
    "Dungeons Catacombs Floor 4 Fastest Time S+": "dungeons_catacombs_floor_4_fastest_time_s+",
    "Kills Phantom Spirit": "kills_phantom_spirit",
    "Dungeons Catacombs Floor 7 Fastest Time S": "dungeons_catacombs_floor_7_fastest_time_s",
    "Deaths Crypt Undead Thorlon": "deaths_crypt_undead_thorlon",
    "Deaths Jockey Shot Silverfish": "deaths_jockey_shot_silverfish",
    "Deaths Crypt Lurker": "deaths_crypt_lurker",
    "Minion Magma Cube Kills": "kills_generator_magma_cube",
    "Player K/D": "player_kills_k/d",
    "Dungeon Hub Precursor Ruins No Pearls With Return Best Time": "dungeon_hub_precursor_ruins_no_pearls_with_return_best_time",
    "Deaths Watcher Scarf": "deaths_watcher_scarf",
    "Dungeon Hub Precursor Ruins No Abilities No Return Best Time": "dungeon_hub_precursor_ruins_no_abilities_no_return_best_time",
    "Slayer Xp": "slayer_xp",
    "Kills Spider Jockey": "kills_spider_jockey",
    "Kills Runic Zombie": "kills_runic_zombie",
    "Crypt Ghoul Kills": "kills_unburried_zombie",
    "Deaths Crypt Undead Orangemarshall": "deaths_crypt_undead_orangemarshall",
    "Kills Thorn": "kills_thorn",
    "Deaths Scarf": "deaths_scarf",
    "Dungeon Hub Precursor Ruins Nothing No Return Best Time": "dungeon_hub_precursor_ruins_nothing_no_return_best_time",
    "Deaths Sheep": "deaths_sheep",
    "Minion Ghast Deaths": "deaths_generator_ghast",
    "Kills Crypt Undead Sylent": "kills_crypt_undead_sylent",
    "Kills Redstone Pigman": "kills_redstone_pigman",
    "Kills Horseman Horse": "kills_horseman_horse",
    "Mythos Burrows Dug Combat Null": "mythos_burrows_dug_combat_null",
    "Deaths Sea Emperor": "deaths_sea_emperor",
    "Deaths Professor Priest Guardian": "deaths_professor_priest_guardian",
    "Deaths Wither": "deaths_wither",
    "Dungeons Catacombs Floor 4 Most Healing": "dungeons_catacombs_floor_4_most_healing",
    "Deaths Wither Miner": "deaths_wither_miner",
    "Dungeons Catacombs Floor 2 Most Damage Archer": "dungeons_catacombs_floor_2_most_damage_archer",
    "Dungeon Hub Precursor Ruins No Pearls No Return Best Time": "dungeon_hub_precursor_ruins_no_pearls_no_return_best_time",
    "Kills Zombie Grunt": "kills_zombie_grunt",
    "Deaths Scarf Archer": "deaths_scarf_archer",
    "Kills Gaia Construct": "kills_gaia_construct",
    "Mythos Burrows Dug Treasure": "mythos_burrows_dug_treasure",
    "Kills Skeleton Soldier": "kills_skeleton_soldier",
}

PET_XP_TABLE = {
    "Common": {
        1: 0,
        2: 100,
        3: 210,
        4: 330,
        5: 460,
        6: 605,
        7: 765,
        8: 940,
        9: 1130,
        10: 1340,
        11: 1570,
        12: 1820,
        13: 2095,
        14: 2395,
        15: 2725,
        16: 3085,
        17: 3485,
        18: 3925,
        19: 4415,
        20: 4955,
        21: 5555,
        22: 6215,
        23: 6945,
        24: 7745,
        25: 8625,
        26: 9585,
        27: 10635,
        28: 11785,
        29: 13045,
        30: 14425,
        31: 15935,
        32: 17585,
        33: 19385,
        34: 21345,
        35: 23475,
        36: 25785,
        37: 28285,
        38: 30985,
        39: 33905,
        40: 37065,
        41: 40485,
        42: 44185,
        43: 48185,
        44: 52535,
        45: 57285,
        46: 62485,
        47: 68185,
        48: 74485,
        49: 81485,
        50: 89285,
        51: 97985,
        52: 107685,
        53: 118485,
        54: 130485,
        55: 143785,
        56: 158485,
        57: 174685,
        58: 192485,
        59: 211985,
        60: 233285,
        61: 256485,
        62: 281685,
        63: 309085,
        64: 338885,
        65: 371285,
        66: 406485,
        67: 444685,
        68: 486085,
        69: 530885,
        70: 579285,
        71: 631485,
        72: 687685,
        73: 748085,
        74: 812885,
        75: 882285,
        76: 956485,
        77: 1035685,
        78: 1120385,
        79: 1211085,
        80: 1308285,
        81: 1412485,
        82: 1524185,
        83: 1643885,
        84: 1772085,
        85: 1909285,
        86: 2055985,
        87: 2212685,
        88: 2380385,
        89: 2560085,
        90: 2752785,
        91: 2959485,
        92: 3181185,
        93: 3418885,
        94: 3673585,
        95: 3946285,
        96: 4237985,
        97: 4549685,
        98: 4883385,
        99: 5241085,
        100: 5624785,
    },
    "Uncommon": {
        1: 0,
        2: 175,
        3: 365,
        4: 575,
        5: 805,
        6: 1055,
        7: 1330,
        8: 1630,
        9: 1960,
        10: 2320,
        11: 2720,
        12: 3160,
        13: 3650,
        14: 4190,
        15: 4790,
        16: 5450,
        17: 6180,
        18: 6980,
        19: 7860,
        20: 8820,
        21: 9870,
        22: 11020,
        23: 12280,
        24: 13660,
        25: 15170,
        26: 16820,
        27: 18620,
        28: 20580,
        29: 22710,
        30: 25020,
        31: 27520,
        32: 30220,
        33: 33140,
        34: 36300,
        35: 39720,
        36: 43420,
        37: 47420,
        38: 51770,
        39: 56520,
        40: 61720,
        41: 67420,
        42: 73720,
        43: 80720,
        44: 88520,
        45: 97220,
        46: 106920,
        47: 117720,
        48: 129720,
        49: 143020,
        50: 157720,
        51: 173920,
        52: 191720,
        53: 211220,
        54: 232520,
        55: 255720,
        56: 280920,
        57: 308320,
        58: 338120,
        59: 370520,
        60: 405720,
        61: 443920,
        62: 485320,
        63: 530120,
        64: 578520,
        65: 630720,
        66: 686920,
        67: 747320,
        68: 812120,
        69: 881520,
        70: 955720,
        71: 1034920,
        72: 1119620,
        73: 1210320,
        74: 1307520,
        75: 1411720,
        76: 1523420,
        77: 1643120,
        78: 1771320,
        79: 1908520,
        80: 2055220,
        81: 2211920,
        82: 2379620,
        83: 2559320,
        84: 2752020,
        85: 2958720,
        86: 3180420,
        87: 3418120,
        88: 3672820,
        89: 3945520,
        90: 4237220,
        91: 4548920,
        92: 4882620,
        93: 5240320,
        94: 5624020,
        95: 6035720,
        96: 6477420,
        97: 6954120,
        98: 7470820,
        99: 8032520,
        100: 8644220,
    },
    "Rare": {
        1: 0,
        2: 275,
        3: 575,
        4: 905,
        5: 1265,
        6: 1665,
        7: 2105,
        8: 2595,
        9: 3135,
        10: 3735,
        11: 4395,
        12: 5125,
        13: 5925,
        14: 6805,
        15: 7765,
        16: 8815,
        17: 9965,
        18: 11225,
        19: 12605,
        20: 14115,
        21: 15765,
        22: 17565,
        23: 19525,
        24: 21655,
        25: 23965,
        26: 26465,
        27: 29165,
        28: 32085,
        29: 35245,
        30: 38665,
        31: 42365,
        32: 46365,
        33: 50715,
        34: 55465,
        35: 60665,
        36: 66365,
        37: 72665,
        38: 79665,
        39: 87465,
        40: 96165,
        41: 105865,
        42: 116665,
        43: 128665,
        44: 141965,
        45: 156665,
        46: 172865,
        47: 190665,
        48: 210165,
        49: 231465,
        50: 254665,
        51: 279865,
        52: 307265,
        53: 337065,
        54: 369465,
        55: 404665,
        56: 442865,
        57: 484265,
        58: 529065,
        59: 577465,
        60: 629665,
        61: 685865,
        62: 746265,
        63: 811065,
        64: 880465,
        65: 954665,
        66: 1033865,
        67: 1118565,
        68: 1209265,
        69: 1306465,
        70: 1410665,
        71: 1522365,
        72: 1642065,
        73: 1770265,
        74: 1907465,
        75: 2054165,
        76: 2210865,
        77: 2378565,
        78: 2558265,
        79: 2750965,
        80: 2957665,
        81: 3179365,
        82: 3417065,
        83: 3671765,
        84: 3944465,
        85: 4236165,
        86: 4547865,
        87: 4881565,
        88: 5239265,
        89: 5622965,
        90: 6034665,
        91: 6476365,
        92: 6953065,
        93: 7469765,
        94: 8031465,
        95: 8643165,
        96: 9309865,
        97: 10036565,
        98: 10828265,
        99: 11689965,
        100: 12626665,
    },
    "Epic": {
        1: 0,
        2: 440,
        3: 930,
        4: 1470,
        5: 2070,
        6: 2730,
        7: 3460,
        8: 4260,
        9: 5140,
        10: 6100,
        11: 7150,
        12: 8300,
        13: 9560,
        14: 10940,
        15: 12450,
        16: 14100,
        17: 15900,
        18: 17860,
        19: 19990,
        20: 22300,
        21: 24800,
        22: 27500,
        23: 30420,
        24: 33580,
        25: 37000,
        26: 40700,
        27: 44700,
        28: 49050,
        29: 53800,
        30: 59000,
        31: 64700,
        32: 71000,
        33: 78000,
        34: 85800,
        35: 94500,
        36: 104200,
        37: 115000,
        38: 127000,
        39: 140300,
        40: 155000,
        41: 171200,
        42: 189000,
        43: 208500,
        44: 229800,
        45: 253000,
        46: 278200,
        47: 305600,
        48: 335400,
        49: 367800,
        50: 403000,
        51: 441200,
        52: 482600,
        53: 527400,
        54: 575800,
        55: 628000,
        56: 684200,
        57: 744600,
        58: 809400,
        59: 878800,
        60: 953000,
        61: 1032200,
        62: 1116900,
        63: 1207600,
        64: 1304800,
        65: 1409000,
        66: 1520700,
        67: 1640400,
        68: 1768600,
        69: 1905800,
        70: 2052500,
        71: 2209200,
        72: 2376900,
        73: 2556600,
        74: 2749300,
        75: 2956000,
        76: 3177700,
        77: 3415400,
        78: 3670100,
        79: 3942800,
        80: 4234500,
        81: 4546200,
        82: 4879900,
        83: 5237600,
        84: 5621300,
        85: 6033000,
        86: 6474700,
        87: 6951400,
        88: 7468100,
        89: 8029800,
        90: 8641500,
        91: 9308200,
        92: 10034900,
        93: 10826600,
        94: 11688300,
        95: 12625000,
        96: 13641700,
        97: 14743400,
        98: 15935100,
        99: 17221800,
        100: 18608500,
    },
    "Legendary": {
        1: 0,
        2: 660,
        3: 1390,
        4: 2190,
        5: 3070,
        6: 4030,
        7: 5080,
        8: 6230,
        9: 7490,
        10: 8870,
        11: 10380,
        12: 12030,
        13: 13830,
        14: 15790,
        15: 17920,
        16: 20230,
        17: 22730,
        18: 25430,
        19: 28350,
        20: 31510,
        21: 34930,
        22: 38630,
        23: 42630,
        24: 46980,
        25: 51730,
        26: 56930,
        27: 62630,
        28: 68930,
        29: 75930,
        30: 83730,
        31: 92430,
        32: 102130,
        33: 112930,
        34: 124930,
        35: 138230,
        36: 152930,
        37: 169130,
        38: 186930,
        39: 206430,
        40: 227730,
        41: 250930,
        42: 276130,
        43: 303530,
        44: 333330,
        45: 365730,
        46: 400930,
        47: 439130,
        48: 480530,
        49: 525330,
        50: 573730,
        51: 625930,
        52: 682130,
        53: 742530,
        54: 807330,
        55: 876730,
        56: 950930,
        57: 1030130,
        58: 1114830,
        59: 1205530,
        60: 1302730,
        61: 1406930,
        62: 1518630,
        63: 1638330,
        64: 1766530,
        65: 1903730,
        66: 2050430,
        67: 2207130,
        68: 2374830,
        69: 2554530,
        70: 2747230,
        71: 2953930,
        72: 3175630,
        73: 3413330,
        74: 3668030,
        75: 3940730,
        76: 4232430,
        77: 4544130,
        78: 4877830,
        79: 5235530,
        80: 5619230,
        81: 6030930,
        82: 6472630,
        83: 6949330,
        84: 7466030,
        85: 8027730,
        86: 8639430,
        87: 9306130,
        88: 10032830,
        89: 10824530,
        90: 11686230,
        91: 12622930,
        92: 13639630,
        93: 14741330,
        94: 15933030,
        95: 17219730,
        96: 18606430,
        97: 20103130,
        98: 21719830,
        99: 23466530,
        100: 25353230,
    },
}

SKILL_WEIGHT_VALUES = {
    "experience_skill_combat": {"exponent": 1.15797687265, "divider": 275862},
    "experience_skill_mining": {"exponent": 1.18207448, "divider": 259634},
    "experience_skill_farming": {"exponent": 1.217848139, "divider": 220689},
    "experience_skill_fishing": {"exponent": 1.406418, "divider": 88274},
    "experience_skill_foraging": {"exponent": 1.232826, "divider": 259634},
    "experience_skill_taming": {"exponent": 1.14744, "divider": 441379},
    "experience_skill_alchemy": {"exponent": 1.0, "divider": 1103448},
    "experience_skill_enchanting": {"exponent": 0.96976583, "divider": 882758},
}

SLAYER_WEIGHT_VALUES = {"zombie": 2208, "spider": 2118, "wolf": 1962}

DUNGEON_WEIGHT_VALUES = {
    "catacomb": 0.0002149604615,
    "healer": 0.0000045254834,
    "mage": 0.0000045254834,
    "berserk": 0.0000045254834,
    "tank": 0.0000045254834,
    "archer": 0.0000045254834,
}

FUEL_SPEEDS = {
    "beacon_base_tier": 2,
    "hamster_wheels": 50,
    "foul_flesh": 90,
    "enchanted_lava_bucket": 25,
    "magma_bucket": 30,
    "plasma_bucket": 35,
    "fly_catcher": 20,
    "minion_expander": 5,
    "pet": 0.3,
    "crystal": 10,
}

LIMITS = {
    "Sugarcane": 712530,
    "Potato": 1068795,
    "Carrot": 1068795,
    "Wheat": 356265,
    "Nether Wart": 890662,
    "Pumpkin": 147960,
    "Melon": 739800,
}

SKYBLOCK_YEAR_114 = 1610718900
SKYBLOCK_YEAR_LENGTH = 446400
SKYBLOCK_MONTH_LENGTH = 37200
SKYBLOCK_DAY_LENGTH = 1200
